spring:
  application:
    name: dishProvider

OPENAI_API_KEY: ${ENV_OPENAI_API_KEY:2365}
openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
APP_API_KEY: ${ENV_APP_API_KEY:2365}
server:
  error:
    include-message: always
    include-binding-errors: always

